### ISSUE TITLE
A couple of problems about exercise A36

### ISSUE THREAD

**Issue by username-011** [jayson-lennon/ztm-rust#6]
1. The iterator of data().chunks() is &[u64] and not Option<&[u64]>. The video also proves that since we never handle the Option or unwrap it anywhere, also in IDE I guess.
![image](https://github.com/jayson-lennon/ztm-rust/assets/68825567/4c7828d9-04f9-418b-8558-1e9991c829a2)
2. "If no numbers are received print 'data stream is complete'" statement is also incorrect. In this case, as long as there are items in the slice, it will always return either [a, b] or just [a]. As far as I tested, _this_ iterator simply does not produce [] in any case(unreachable?), so that statement doesn't really make sense. We can see that when the stream actually completes, we just get the unpaired value last.
![image](https://github.com/jayson-lennon/ztm-rust/assets/68825567/3db08bda-c277-4fef-be3a-bdb4366e1fcb)
3. The stream does not need to be mutable.

**Comment by jayson-lennon** [comment]
I've modified the requirements to exclude the statement about data stream completion. This is not needed since the `for` loop finishing indicates completion.. Thanks for the feedback.

**Comment by username-011** [comment]
@jayson-lennon 
I see, thanks for fixing it! But a couple of minutes later I also mentioned points 1 and 3, I would appreciate if you also take a look at them.

**Comment by jayson-lennon** [comment]
For 1: I'm not sure what is meant by point 1. I'm not seeing any `Option` in the code.

For 3: This change was made when I fixed the program requirements.

See https://github.com/jayson-lennon/ztm-rust/commit/ef09158607457118e30a354f70072e0f4539f590 for changes

**Comment by username-011** [comment]
@jayson-lennon 
For 1. Yes, there is no Option in the code, yet there is Option in the comment to the exercise.
![image](https://github.com/jayson-lennon/ztm-rust/assets/68825567/ea6b8c7c-adec-4921-b9fc-b6d81f138ef5) \
On the line 17, "stream is an iterator of Option<&[u64]>"
For 3. I see it is indeed fixed now in https://github.com/jayson-lennon/ztm-rust/commit/ef09158607457118e30a354f70072e0f4539f590

**Comment by jayson-lennon** [comment]
This has now been corrected. Thanks!
